# Generated by Django 5.1.4 on 2024-12-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
